version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - "./nginx:/etc/nginx/conf.d"
      - "../:/var/www/html"
    links:
      - php
  php:
    build: php
    volumes:
      - "../:/var/www/html"
  db:
    image: postgres
    ports:
      - "5433:5432"
    env_file:
      - ./pgsql/db.env
    volumes:
      - ../db-data:/var/lib/postgresql/data